void printhands();
void updateptotal();
void updatedtotal();
void hitdeal();
void recomputeptotal();
void resolvedeal();
int pdecision();
void splitdeal();
void play();
void cleartable();
void opendraw();
int verb(int);
int openbet();
bool handbust();
bool trialover(int);
void read_params(char*);
void swap(int*, int*);
void shuffle(int*, int);
void initialize_shoe(int*, int);
