void printhands();
void updateptotal();
void updatedtotal();
void hitdeal();
void recomputeptotal();
void resolvedeal();
int pdecision();
void splitdeal();
void play(int);
void cleartable();
void opendraw();
float verb(int);
float openbet();
bool handbust();
bool trialover(int);
void read_params(char*);
void swap(int*, int*);
void shuffle(int*, int);
void initialize_shoe(int*, int);
void compute_stats();
void write_stats(char*);
void update_shoe_counts(int);
void print_shoe_counts();
void write_hist();
void write_ghist();
